/**
 * Traductions de l'ÉDITORIAL des pages internes v3 (hero, titres de sections,
 * intros, cartes, étapes, boutons, CTA) — FR / NL / EN.
 *
 * Le contenu « base de données » (réponses de FAQ, cellules de tarifs, pièces
 * des fiches pays) reste en français en attendant une traduction dédiée.
 */

import type { Locale } from "./i18n";

type Dict = Record<string, string>;

const FR: Dict = {
  // communs
  cta_devis: "Obtenir un devis",
  cta_conseiller: "Parler à un conseiller",
  cta_contact: "Nous contacter",
  cta_ecrire: "Nous écrire",
  voir_tarifs: "Voir les tarifs",
  q_freq: "Questions fréquentes",
  tarifs_delais: "Tarifs et délais",
  le_deroulement: "Le déroulement",
  deroulement_h: "Simple. Clair. Accompagné.",

  // VISAS
  vi_eb: "Service · Visas de voyage",
  vi_h1a: "Visas, e-visas",
  vi_h1g: "& autorisations.",
  vi_sub: "Tourisme, affaires ou e-visa : les règles varient selon le pays et changent souvent. Nous vérifions les conditions qui s’appliquent à votre situation, réunissons les pièces et suivons votre demande.",
  vi_stat: "destinations couvertes",
  vi_types_eb: "Types de visa",
  vi_types_h: "Quel visa pour votre voyage ?",
  vi_t1h: "Visa tourisme", vi_t1p: "Séjour de loisirs, visite familiale ou amicale. Constitution du dossier et rendez-vous consulaire.",
  vi_t2h: "Visa affaires", vi_t2p: "Missions, salons, réunions. Vérification de la lettre d’invitation et des justificatifs incluse.",
  vi_t3h: "e-Visa", vi_t3p: "Demande en ligne (Inde, Égypte, Vietnam…). Saisie, vérification et suivi jusqu’à l’émission.",
  vi_t4h: "Autorisations de voyage", vi_t4p: "Autorisations électroniques de voyage (type eTA, K-ETA). Nous préparons et suivons la demande d’autorisation.",
  vi_dest_eb: "Destinations et fiches pays",
  vi_dest_h: "Chaque destination a sa page détaillée.",
  vi_dest_p: "Procédure, pièces à fournir, délai et tarifs, mis à jour sur sources officielles.",
  vi_dest_more: "Voir les {n} destinations →",
  vi_s1: "Vous indiquez votre destination et le motif", vi_s1p: "En une phrase, en ligne ou par téléphone.",
  vi_s2: "Nous vérifions les conditions applicables", vi_s2p: "Type de visa, documents, délais et consulat compétent.",
  vi_s3: "Vous nous confiez votre dossier et votre passeport", vi_s3p: "En ligne ou au bureau de l’avenue Louise.",
  vi_s4: "Nous déposons, suivons et récupérons", vi_s4p: "Rendez-vous consulaire, dépôt et remise du passeport.",
  vi_tar_h: "Nos honoraires, par destination.",
  vi_tar_p: "Honoraires du bureau, hors frais consulaires. Chaque fiche pays publie la grille détaillée du consulat concerné.",
  vi_grille: "Voir la grille complète →",
  vi_faq_h: "Les questions sur les visas.",
  vi_cta_h: "Préparez votre dossier de visa.",
  vi_cta_p: "Indiquez votre destination et le motif du séjour : nous vérifions les conditions applicables et la liste des pièces.",

  // TRADUCTIONS
  tr_eb: "Service · Traductions",
  tr_h1a: "Traductions",
  tr_h1g: "assermentées & libres.",
  tr_sub: "Assermentée (jurée) pour vos actes officiels, ou libre pour l’information : nous vous indiquons celle qu’exige votre démarche, puis produisons une traduction fidèle et conforme, reconnue par les autorités belges et étrangères.",
  tr_stat: "langues traitées",
  tr_f1: "langues", tr_f1p: "À partir et vers toute autre langue.",
  tr_f2: "traducteurs", tr_f2p: "Assermentés près les tribunaux belges.",
  tr_f3: "délai standard", tr_f3p: "Prioritaire 48 h, express 24 h.",
  tr_f4: "dépôt & retrait", tr_f4p: "Au bureau ou en ligne.",
  tr_two_eb: "Deux types de traduction",
  tr_two_h: "Laquelle votre démarche exige-t-elle ?",
  tr_c1h: "Traduction assermentée (jurée)", tr_c1p: "Réalisée par un traducteur juré, avec cachet et signature. Exigée par les administrations, l’état civil, les tribunaux et les démarches à l’étranger.",
  tr_c2h: "Traduction libre", tr_c2p: "Pour l’information, l’usage interne ou commercial : sites web, brochures, correspondances, documents techniques. Même exigence de qualité.",
  tr_doc_eb: "Documents traités",
  tr_doc_h: "Ce que nous traduisons.",
  tr_doc_p: "Une expertise couvrant l’ensemble des besoins légaux, commerciaux et académiques. Si votre document ne figure pas ici, envoyez-le : la réponse arrive le jour même.",
  tr_lang_eb: "Langues",
  tr_lang_h: "{n} langues, de l’albanais au wolof.",
  tr_lang_p: "Traducteurs jurés disponibles pour les principales langues ; traduction libre pour toutes les autres.",
  tr_tar_h: "Nos prix, publiés.",
  tr_faq_h: "Les questions sur la traduction.",
  tr_cta_h: "Faites estimer votre traduction.",
  tr_cta_p: "Un scan lisible suffit pour obtenir un prix ferme et un délai.",

  // LÉGALISATIONS
  lg_eb: "Service · Légalisations",
  lg_h1a: "Légalisations, apostilles",
  lg_h1g: "et dépôts officiels.",
  lg_sub: "Nous prenons en charge l’intégralité du processus de légalisation de vos documents auprès des instances belges et des représentations diplomatiques étrangères. Un seul interlocuteur, du premier guichet au dernier.",
  lg_stat: "instances couvertes",
  lg_two_eb: "Deux voies possibles",
  lg_two_h: "Apostille, ou légalisation complète ?",
  lg_c1h: "Apostille de La Haye", lg_c1p: "Pour les pays signataires de la Convention de La Haye : un seul cachet du SPF Affaires étrangères suffit. Procédure la plus rapide.",
  lg_c2h: "Légalisation complète", lg_c2p: "Pour les autres pays : la chaîne se poursuit jusqu’à l’ambassade ou au consulat de destination. Nous en assurons chaque maillon.",
  lg_ch_eb: "La chaîne de légalisation",
  lg_ch_h: "Le bon guichet, dans le bon ordre.",
  lg_ch_p: "Chaque maillon suppose de connaître le bon guichet, le bon ordre et les bonnes pièces. Une erreur au début de la chaîne se paie à la fin, en semaines perdues.",
  lg_s1: "Nous vérifions la voie applicable", lg_s1p: "Apostille de La Haye ou légalisation complète, selon le pays de destination.",
  lg_s2: "Légalisations belges", lg_s2p: "Tribunal de première instance, SPF Justice, SPF Affaires étrangères (apostille), chambre de commerce.",
  lg_s3: "Représentation diplomatique", lg_s3p: "Dépôt au consulat ou à l’ambassade du pays lorsque l’apostille ne suffit pas.",
  lg_s4: "Remise du dossier finalisé", lg_s4p: "En main propre au bureau ou par envoi sécurisé.",
  lg_inst_eb: "Instances couvertes",
  lg_inst_h: "Nous traitons directement avec :",
  lg_tar_h: "Frais officiels et honoraires, distingués.",
  lg_tar_p: "Les frais officiels réclamés par l’administration ou le consulat sont refacturés à l’euro près, sur justificatif, et distincts des honoraires du bureau.",
  lg_faq_h: "Les questions sur la légalisation.",
  lg_cta_h: "Besoin de légaliser vos documents ?",
  lg_cta_p: "Obtenez une analyse précise de votre dossier et un devis détaillé sous 2 heures ouvrables.",

  // TARIFS
  ta_eb: "Tarifs et délais",
  ta_h1a: "Les prix,",
  ta_h1g: "avant de décrocher le téléphone.",
  ta_sub: "Le bureau publie ses prix. C’est la première question de tout visiteur, et la réponse ne devrait pas exiger un appel téléphonique. Les frais officiels sont toujours distingués des honoraires.",
  ta_cta1: "Envoyer mes documents",
  ta_stat: "devis ferme, en heures ouvrables",
  ta_trad: "Traduction", ta_trad_h: "Traductions libres et assermentées.",
  ta_leg: "Légalisation", ta_leg_h: "Légalisations et apostilles.",
  ta_visa: "Visa", ta_visa_h: "Visas par destination.",
  ta_cov_eb: "Ce que couvre le prix", ta_cov_h: "Sans mauvaise surprise.",
  ta_cov1h: "Frais officiels distingués", ta_cov1p: "Les montants réclamés par les administrations et consulats sont refacturés à l’euro près, sur justificatif.",
  ta_cov2h: "Aucune marge cachée", ta_cov2p: "Le bureau ne prend aucune marge sur les frais officiels ; ses honoraires sont annoncés d’avance.",
  ta_cov3h: "Devis ferme en 2 h", ta_cov3p: "Un scan de vos documents suffit : vous recevez le détail poste par poste, en heures ouvrables.",
  ta_faq_h: "Ce qu’il faut savoir.",
  ta_cta_h: "Un chiffre ferme, pas une fourchette.",
  ta_cta_p: "Envoyez le scan de vos documents et votre destination : vous recevez le détail poste par poste, frais officiels distingués des honoraires.",
  ta_cta1b: "Obtenir mon devis",

  // RESSOURCES
  re_eb: "Ressources",
  re_h1a: "Guides, procédures",
  re_h1g: "et listes de pièces.",
  re_sub: "Les réponses aux questions qui reviennent le plus au téléphone, écrites une fois pour toutes. Consultables à toute heure, y compris quand le bureau est fermé.",
  re_stat: "fiches pays",
  re_g_eb: "Guides", re_g_h: "Comprendre avant de se déplacer.",
  re_g1h: "Traduction jurée ou libre ?", re_g1p: "Comprendre quand un cachet de traducteur juré est exigé, et quand une traduction libre suffit.",
  re_g2h: "La chaîne de légalisation", re_g2p: "Apostille de La Haye ou légalisation complète : le bon ordre des guichets, du tribunal à l’ambassade.",
  re_g3h: "Choisir sa procédure de visa", re_g3p: "Visa consulaire ou e-visa : comment savoir ce qu’exige votre destination.",
  re_g_more: "Lire le guide",
  re_l_eb: "Listes de pièces", re_l_h: "Savoir exactement quoi rassembler.",
  re_l_p: "Chaque fiche pays publie la liste des pièces à fournir, le délai et les tarifs, mis à jour sur sources officielles. {n} destinations couvertes.",
  re_l_btn: "Voir les fiches pays",
  re_faq_h: "Les questions qui reviennent.",
  re_cta_h: "Une question que ces guides ne couvrent pas ?",
  re_cta_p: "Le bureau répond de manière claire et rapide, du lundi au vendredi de 9 h à 17 h sans interruption.",

  // À PROPOS
  ap_eb: "Le bureau",
  ap_h1a: "Le bureau,",
  ap_h1g: "avenue Louise.",
  ap_sub: "{r} accompagne particuliers et entreprises dans leurs démarches documentaires internationales : traduction jurée, légalisation et visas de voyage. Les technologies nous font gagner du temps ; nos experts restent au cœur de chaque dossier.",
  ap_stat: "vues sur la fiche Google Local Guide",
  ap_visite: "Nous rendre visite",
  ap_lead: "Une démarche officielle à l’étranger, sans la corvée administrative.",
  ap_metier: "Notre métier",
  ap_metier1: "Une démarche officielle, c’est souvent plusieurs guichets, un ordre précis à respecter et des pièces exactes à réunir. Nous connaissons ces chaînes et nous les parcourons pour vous.",
  ap_metier2: "À chaque étape, nous vous disons quoi fournir, à quel prix et dans quel délai — jusqu’à l’acceptation du dossier.",
  ap_ph_lab: "Emplacement", ap_ph_h: "Photo de l’équipe Travisum à intégrer", ap_ph_p: "Photo professionnelle prise au bureau de l’avenue Louise. Format 1600 × 1000 px.",
  ap_eng_eb: "Nos engagements", ap_eng_h: "Ce sur quoi nous nous engageons.",
  ap_e1h: "Confidentialité", ap_e1p: "Passeports, actes, diplômes : transmission chiffrée, accès limité à l’équipe en charge, copies supprimées après traitement.",
  ap_e2h: "Des prix publiés", ap_e2p: "Nos tarifs sont en ligne. Les frais officiels sont refacturés à l’euro près, sur justificatif, sans marge.",
  ap_e3h: "Un seul interlocuteur", ap_e3p: "De la traduction jurée au dépôt du visa, une seule équipe suit votre dossier de bout en bout.",
  ap_conf_eb: "Confidentialité", ap_conf_h: "Vous nous confiez des originaux. Nous le prenons au sérieux.",
  ap_conf_p: "Passeports, actes de naissance, diplômes : ce sont des documents que l’on ne confie pas à la légère.",
  ap_conf1: "Documents traités de manière confidentielle par notre équipe.",
  ap_conf2: "Accès limité à l’équipe en charge de votre dossier.",
  ap_conf3: "Suppression des copies numériques après traitement.",
  ap_conf4: "Originaux remis en main propre ou par envoi recommandé.",
  ap_gg_eb: "Avis clients", ap_gg_h: "Notre fiche Google, bientôt connectée au site.",
  ap_gg_p: "Les avis publiés sur la fiche Google Business Profile de Travisum Louise Office s’afficheront ici automatiquement, avec la note et le nombre d’avis réels. Aucun témoignage ne sera rédigé.",
  ap_gg_btn: "Voir la fiche Google", ap_gg_lab: "Emplacement", ap_gg_sub: "vues sur la fiche Google Local Guide — chiffre à vérifier et à mettre à jour.",
  ap_ct_eb: "Le bureau",
  ap_ct_tel: "Téléphone", ap_ct_mail: "E-mail", ap_ct_acces: "Accès", ap_ct_acces_v: "métro Louise, trams 8 et 93, bus 54.",
  ap_ct_maps: "Ouvrir dans Google Maps",
  ap_hor: "du lundi au vendredi, sans interruption",
  ap_cta_h: "Passez au bureau, ou envoyez un scan.",
  ap_cta_p: "Rendez-vous et conseils personnalisés également possibles, sur simple demande.",

  // FICHE PAYS
  pp_dest: "Destination",
  pp_h1: "Visa",
  pp_sub: "Procédure, pièces à fournir, délai et tarifs pour une demande déposée depuis la Belgique. Le bureau constitue le dossier, prend le rendez-vous consulaire, dépose et récupère votre passeport.",
  pp_lancer: "Lancer ma demande",
  fil_accueil: "Accueil", fil_visas: "Visas", fil_aria: "Fil d’Ariane",
  pp_pieces_eb: "Pièces à fournir", pp_pieces_h: "Documents et procédures.",
  pp_prep_eb: "Cette destination", pp_prep_h: "Fiche en cours de rédaction.",
  pp_prep_p: "Le bureau traite cette destination, mais le détail des pièces n’est pas encore publié. Contactez-nous : la réponse arrive le jour même.",
  pp_autres_eb: "Autres destinations", pp_autres_h: "Voir aussi.",
  pp_fiche: "Fiche pays",
  pp_toutes: "Les {n} destinations →",
  pp_cta_h: "Préparez votre dossier {a}.",
  pp_cta_p: "Envoyez-nous votre passeport en scan et le motif du séjour : nous vérifions les conditions applicables et la liste des pièces.",
  vol_tourisme: "Visa tourisme", vol_business: "Visa affaires", vol_evisa: "e-Visa", vol_infos: "Informations générales", vol_autre: "Autre procédure",
  syn_lab: "Synthèse visa — à jour", syn_verif: "Vérifié le", syn_portail: "Portail officiel", syn_frais: "Frais officiels (indicatifs)", syn_delai: "Délai de traitement", syn_validite: "Validité / séjour", syn_reforme: "Changement récent —", syn_source: "Source",
  syn_disc: "Informations indicatives, vérifiées sur source officielle et susceptibles d’évoluer. La décision appartient au consulat.",
  locale: "fr-BE",
};

const NL: Dict = {
  cta_devis: "Offerte aanvragen",
  cta_conseiller: "Een adviseur spreken",
  cta_contact: "Contact opnemen",
  cta_ecrire: "Schrijf ons",
  voir_tarifs: "Tarieven bekijken",
  q_freq: "Veelgestelde vragen",
  tarifs_delais: "Tarieven en termijnen",
  le_deroulement: "Het verloop",
  deroulement_h: "Eenvoudig. Duidelijk. Begeleid.",

  vi_eb: "Dienst · Reisvisa",
  vi_h1a: "Visa, e-visa",
  vi_h1g: "& autorisaties.",
  vi_sub: "Toerisme, zaken of e-visum: de regels verschillen per land en veranderen vaak. Wij controleren de voorwaarden voor uw situatie, verzamelen de stukken en volgen uw aanvraag op.",
  vi_stat: "bestemmingen",
  vi_types_eb: "Types visum",
  vi_types_h: "Welk visum voor uw reis?",
  vi_t1h: "Toeristenvisum", vi_t1p: "Vakantie, familie- of vriendenbezoek. Samenstelling van het dossier en consulaire afspraak.",
  vi_t2h: "Zakenvisum", vi_t2p: "Missies, beurzen, vergaderingen. Controle van de uitnodigingsbrief en bewijsstukken inbegrepen.",
  vi_t3h: "e-Visum", vi_t3p: "Online aanvraag (India, Egypte, Vietnam…). Invoer, controle en opvolging tot de afgifte.",
  vi_t4h: "Reisautorisaties", vi_t4p: "Elektronische reisautorisaties (type eTA, K-ETA). Wij bereiden de aanvraag voor en volgen ze op.",
  vi_dest_eb: "Bestemmingen en landfiches",
  vi_dest_h: "Elke bestemming heeft haar eigen pagina.",
  vi_dest_p: "Procedure, aan te leveren stukken, termijn en tarieven, bijgewerkt op officiële bronnen.",
  vi_dest_more: "Alle {n} bestemmingen bekijken →",
  vi_s1: "U geeft uw bestemming en het motief op", vi_s1p: "In één zin, online of per telefoon.",
  vi_s2: "Wij controleren de geldende voorwaarden", vi_s2p: "Type visum, documenten, termijnen en bevoegd consulaat.",
  vi_s3: "U bezorgt ons uw dossier en paspoort", vi_s3p: "Online of op ons kantoor aan de Louizalaan.",
  vi_s4: "Wij dienen in, volgen op en halen af", vi_s4p: "Consulaire afspraak, indiening en afgifte van het paspoort.",
  vi_tar_h: "Onze honoraria, per bestemming.",
  vi_tar_p: "Honoraria van het kantoor, exclusief consulaire kosten. Elke landfiche publiceert de gedetailleerde tabel van het betrokken consulaat.",
  vi_grille: "Volledige tabel bekijken →",
  vi_faq_h: "Vragen over visa.",
  vi_cta_h: "Bereid uw visumdossier voor.",
  vi_cta_p: "Geef uw bestemming en het reismotief op: wij controleren de geldende voorwaarden en de lijst met stukken.",

  tr_eb: "Dienst · Vertalingen",
  tr_h1a: "Vertalingen",
  tr_h1g: "beëdigd & vrij.",
  tr_sub: "Beëdigd voor uw officiële akten, of vrij voor informatie: wij zeggen u welke uw procedure vereist en leveren een getrouwe, conforme vertaling, erkend door Belgische en buitenlandse autoriteiten.",
  tr_stat: "behandelde talen",
  tr_f1: "talen", tr_f1p: "Van en naar elke andere taal.",
  tr_f2: "vertalers", tr_f2p: "Beëdigd bij de Belgische rechtbanken.",
  tr_f3: "standaardtermijn", tr_f3p: "Prioritair 48 u, express 24 u.",
  tr_f4: "indienen & afhalen", tr_f4p: "Op kantoor of online.",
  tr_two_eb: "Twee soorten vertaling",
  tr_two_h: "Welke vereist uw procedure?",
  tr_c1h: "Beëdigde vertaling", tr_c1p: "Door een beëdigd vertaler, met stempel en handtekening. Vereist door administraties, burgerlijke stand, rechtbanken en buitenlandse procedures.",
  tr_c2h: "Vrije vertaling", tr_c2p: "Voor informatie, intern of commercieel gebruik: websites, brochures, correspondentie, technische documenten. Dezelfde kwaliteitseis.",
  tr_doc_eb: "Behandelde documenten",
  tr_doc_h: "Wat wij vertalen.",
  tr_doc_p: "Expertise die alle juridische, commerciële en academische behoeften dekt. Staat uw document er niet bij? Stuur het op: u krijgt dezelfde dag antwoord.",
  tr_lang_eb: "Talen",
  tr_lang_h: "{n} talen, van Albanees tot Wolof.",
  tr_lang_p: "Beëdigde vertalers voor de belangrijkste talen; vrije vertaling voor alle andere.",
  tr_tar_h: "Onze prijzen, gepubliceerd.",
  tr_faq_h: "Vragen over vertaling.",
  tr_cta_h: "Laat uw vertaling ramen.",
  tr_cta_p: "Een leesbare scan volstaat voor een vaste prijs en termijn.",

  lg_eb: "Dienst · Legalisaties",
  lg_h1a: "Legalisaties, apostilles",
  lg_h1g: "en officiële indieningen.",
  lg_sub: "Wij nemen het volledige legalisatieproces van uw documenten in handen bij de Belgische instanties en de buitenlandse diplomatieke posten. Eén aanspreekpunt, van het eerste tot het laatste loket.",
  lg_stat: "instanties",
  lg_two_eb: "Twee mogelijke wegen",
  lg_two_h: "Apostille of volledige legalisatie?",
  lg_c1h: "Haagse apostille", lg_c1p: "Voor landen die het Verdrag van Den Haag ondertekenden: één stempel van de FOD Buitenlandse Zaken volstaat. De snelste procedure.",
  lg_c2h: "Volledige legalisatie", lg_c2p: "Voor de andere landen: de keten loopt door tot de ambassade of het consulaat van bestemming. Wij verzorgen elke schakel.",
  lg_ch_eb: "De legalisatieketen",
  lg_ch_h: "Het juiste loket, in de juiste volgorde.",
  lg_ch_p: "Elke schakel vereist het juiste loket, de juiste volgorde en de juiste stukken. Een fout aan het begin betaalt u aan het eind, in verloren weken.",
  lg_s1: "Wij bepalen de toe te passen weg", lg_s1p: "Haagse apostille of volledige legalisatie, volgens het land van bestemming.",
  lg_s2: "Belgische legalisaties", lg_s2p: "Rechtbank van eerste aanleg, FOD Justitie, FOD Buitenlandse Zaken (apostille), kamer van koophandel.",
  lg_s3: "Diplomatieke post", lg_s3p: "Indiening bij het consulaat of de ambassade wanneer de apostille niet volstaat.",
  lg_s4: "Afgifte van het afgewerkte dossier", lg_s4p: "Persoonlijk op kantoor of via beveiligde verzending.",
  lg_inst_eb: "Betrokken instanties",
  lg_inst_h: "Wij behandelen rechtstreeks met:",
  lg_tar_h: "Officiële kosten en honoraria, onderscheiden.",
  lg_tar_p: "De officiële kosten van de administratie of het consulaat worden tegen kostprijs doorgerekend, op voorlegging van bewijs, en zijn onderscheiden van de honoraria.",
  lg_faq_h: "Vragen over legalisatie.",
  lg_cta_h: "Documenten te legaliseren?",
  lg_cta_p: "Ontvang een precieze analyse van uw dossier en een gedetailleerde offerte binnen 2 werkuren.",

  ta_eb: "Tarieven en termijnen",
  ta_h1a: "De prijzen,",
  ta_h1g: "vóór u de telefoon neemt.",
  ta_sub: "Het kantoor publiceert zijn prijzen. Het is de eerste vraag van elke bezoeker, en het antwoord zou geen telefoontje mogen vereisen. Officiële kosten worden altijd onderscheiden van de honoraria.",
  ta_cta1: "Mijn documenten sturen",
  ta_stat: "vaste offerte, in werkuren",
  ta_trad: "Vertaling", ta_trad_h: "Vrije en beëdigde vertalingen.",
  ta_leg: "Legalisatie", ta_leg_h: "Legalisaties en apostilles.",
  ta_visa: "Visum", ta_visa_h: "Visa per bestemming.",
  ta_cov_eb: "Wat de prijs dekt", ta_cov_h: "Geen verrassingen.",
  ta_cov1h: "Officiële kosten onderscheiden", ta_cov1p: "De bedragen van administraties en consulaten worden tegen kostprijs doorgerekend, op voorlegging van bewijs.",
  ta_cov2h: "Geen verborgen marge", ta_cov2p: "Het kantoor neemt geen marge op de officiële kosten; de honoraria worden vooraf aangekondigd.",
  ta_cov3h: "Vaste offerte in 2 u", ta_cov3p: "Een scan van uw documenten volstaat: u ontvangt het detail post per post, in werkuren.",
  ta_faq_h: "Wat u moet weten.",
  ta_cta_h: "Een vast bedrag, geen vork.",
  ta_cta_p: "Stuur de scan van uw documenten en uw bestemming: u ontvangt het detail post per post, officiële kosten onderscheiden van de honoraria.",
  ta_cta1b: "Mijn offerte aanvragen",

  re_eb: "Hulpbronnen",
  re_h1a: "Gidsen, procedures",
  re_h1g: "en lijsten van stukken.",
  re_sub: "De antwoorden op de vragen die het vaakst aan de telefoon terugkomen, één keer geschreven. Op elk moment raadpleegbaar, ook als het kantoor gesloten is.",
  re_stat: "landfiches",
  re_g_eb: "Gidsen", re_g_h: "Begrijpen vóór u zich verplaatst.",
  re_g1h: "Beëdigde of vrije vertaling?", re_g1p: "Begrijpen wanneer een stempel van een beëdigd vertaler vereist is en wanneer een vrije vertaling volstaat.",
  re_g2h: "De legalisatieketen", re_g2p: "Haagse apostille of volledige legalisatie: de juiste volgorde van de loketten, van de rechtbank tot de ambassade.",
  re_g3h: "Uw visumprocedure kiezen", re_g3p: "Consulair visum of e-visum: hoe weet u wat uw bestemming vereist.",
  re_g_more: "Gids lezen",
  re_l_eb: "Lijsten van stukken", re_l_h: "Precies weten wat te verzamelen.",
  re_l_p: "Elke landfiche publiceert de lijst met aan te leveren stukken, de termijn en de tarieven, bijgewerkt op officiële bronnen. {n} bestemmingen.",
  re_l_btn: "De landfiches bekijken",
  re_faq_h: "De terugkerende vragen.",
  re_cta_h: "Een vraag die deze gidsen niet dekken?",
  re_cta_p: "Het kantoor antwoordt duidelijk en snel, van maandag tot vrijdag van 9 u tot 17 u doorlopend.",

  ap_eb: "Het kantoor",
  ap_h1a: "Het kantoor,",
  ap_h1g: "Louizalaan.",
  ap_sub: "{r} begeleidt particulieren en bedrijven bij hun internationale documentaire formaliteiten: beëdigde vertaling, legalisatie en reisvisa. Technologie doet ons tijd winnen; onze experts blijven de kern van elk dossier.",
  ap_stat: "weergaven op de Google Local Guide-pagina",
  ap_visite: "Ons bezoeken",
  ap_lead: "Een officiële formaliteit in het buitenland, zonder de administratieve rompslomp.",
  ap_metier: "Ons vak",
  ap_metier1: "Een officiële formaliteit betekent vaak meerdere loketten, een precieze volgorde en exacte stukken. Wij kennen deze ketens en doorlopen ze voor u.",
  ap_metier2: "Bij elke stap zeggen wij u wat u moet aanleveren, tegen welke prijs en binnen welke termijn — tot de aanvaarding van het dossier.",
  ap_ph_lab: "Plaatshouder", ap_ph_h: "Foto van het Travisum-team toe te voegen", ap_ph_p: "Professionele foto genomen op het kantoor aan de Louizalaan. Formaat 1600 × 1000 px.",
  ap_eng_eb: "Onze engagementen", ap_eng_h: "Waarop wij ons engageren.",
  ap_e1h: "Vertrouwelijkheid", ap_e1p: "Paspoorten, akten, diploma’s: versleutelde verzending, toegang beperkt tot het betrokken team, kopieën verwijderd na behandeling.",
  ap_e2h: "Gepubliceerde prijzen", ap_e2p: "Onze tarieven staan online. Officiële kosten worden tegen kostprijs doorgerekend, op voorlegging van bewijs, zonder marge.",
  ap_e3h: "Eén aanspreekpunt", ap_e3p: "Van beëdigde vertaling tot visumindiening volgt één team uw dossier van begin tot eind.",
  ap_conf_eb: "Vertrouwelijkheid", ap_conf_h: "U vertrouwt ons originelen toe. Dat nemen wij ernstig.",
  ap_conf_p: "Paspoorten, geboorteakten, diploma’s: dat zijn documenten die men niet zomaar afgeeft.",
  ap_conf1: "Documenten die vertrouwelijk door ons team worden behandeld.",
  ap_conf2: "Toegang beperkt tot het team dat uw dossier behandelt.",
  ap_conf3: "Digitale kopieën verwijderd na behandeling.",
  ap_conf4: "Originelen persoonlijk overhandigd of aangetekend verzonden.",
  ap_gg_eb: "Klantbeoordelingen", ap_gg_h: "Onze Google-pagina, binnenkort verbonden met de site.",
  ap_gg_p: "De beoordelingen op het Google Business Profile van Travisum Louise Office verschijnen hier automatisch, met de echte score en het echte aantal. Er wordt geen enkele getuigenis geschreven.",
  ap_gg_btn: "De Google-pagina bekijken", ap_gg_lab: "Plaatshouder", ap_gg_sub: "weergaven op de Google Local Guide-pagina — cijfer te verifiëren en bij te werken.",
  ap_ct_eb: "Het kantoor",
  ap_ct_tel: "Telefoon", ap_ct_mail: "E-mail", ap_ct_acces: "Bereikbaarheid", ap_ct_acces_v: "metro Louiza, trams 8 en 93, bus 54.",
  ap_ct_maps: "Openen in Google Maps",
  ap_hor: "van maandag tot vrijdag, doorlopend",
  ap_cta_h: "Kom langs op kantoor, of stuur een scan.",
  ap_cta_p: "Afspraken en persoonlijk advies ook mogelijk, op eenvoudig verzoek.",

  pp_dest: "Bestemming",
  pp_h1: "Visum",
  pp_sub: "Procedure, aan te leveren stukken, termijn en tarieven voor een aanvraag vanuit België. Het kantoor stelt het dossier samen, maakt de consulaire afspraak, dient in en haalt uw paspoort op.",
  pp_lancer: "Mijn aanvraag starten",
  fil_accueil: "Home", fil_visas: "Visa", fil_aria: "Kruimelpad",
  pp_pieces_eb: "Aan te leveren stukken", pp_pieces_h: "Documenten en procedures.",
  pp_prep_eb: "Deze bestemming", pp_prep_h: "Fiche in opmaak.",
  pp_prep_p: "Het kantoor behandelt deze bestemming, maar het detail van de stukken is nog niet gepubliceerd. Contacteer ons: het antwoord komt dezelfde dag.",
  pp_autres_eb: "Andere bestemmingen", pp_autres_h: "Zie ook.",
  pp_fiche: "Landfiche",
  pp_toutes: "De {n} bestemmingen →",
  pp_cta_h: "Bereid uw dossier {a} voor.",
  pp_cta_p: "Stuur ons uw paspoort in scan en het reismotief: wij controleren de geldende voorwaarden en de lijst met stukken.",
  vol_tourisme: "Toeristenvisum", vol_business: "Zakenvisum", vol_evisa: "e-Visum", vol_infos: "Algemene informatie", vol_autre: "Andere procedure",
  syn_lab: "Visumsamenvatting — bijgewerkt", syn_verif: "Gecontroleerd op", syn_portail: "Officieel portaal", syn_frais: "Officiële kosten (indicatief)", syn_delai: "Behandelingstermijn", syn_validite: "Geldigheid / verblijf", syn_reforme: "Recente wijziging —", syn_source: "Bron",
  syn_disc: "Indicatieve informatie, gecontroleerd op officiële bron en onder voorbehoud van wijziging. De beslissing ligt bij het consulaat.",
  locale: "nl-BE",
};

const EN: Dict = {
  cta_devis: "Get a quote",
  cta_conseiller: "Speak to an adviser",
  cta_contact: "Contact us",
  cta_ecrire: "Write to us",
  voir_tarifs: "See pricing",
  q_freq: "Frequently asked questions",
  tarifs_delais: "Pricing and timelines",
  le_deroulement: "The process",
  deroulement_h: "Simple. Clear. Guided.",

  vi_eb: "Service · Travel visas",
  vi_h1a: "Visas, e-visas",
  vi_h1g: "& authorisations.",
  vi_sub: "Tourism, business or e-visa: rules differ by country and change often. We check the conditions that apply to your situation, gather the documents and follow your application.",
  vi_stat: "destinations covered",
  vi_types_eb: "Types of visa",
  vi_types_h: "Which visa for your trip?",
  vi_t1h: "Tourist visa", vi_t1p: "Leisure stay, family or friends visit. File preparation and consular appointment.",
  vi_t2h: "Business visa", vi_t2p: "Missions, trade fairs, meetings. Invitation-letter and supporting-document check included.",
  vi_t3h: "e-Visa", vi_t3p: "Online application (India, Egypt, Vietnam…). Filing, verification and follow-up to issuance.",
  vi_t4h: "Travel authorisations", vi_t4p: "Electronic travel authorisations (e.g. eTA, K-ETA). We prepare and follow up the authorisation request.",
  vi_dest_eb: "Destinations and country pages",
  vi_dest_h: "Every destination has its own detailed page.",
  vi_dest_p: "Procedure, documents, timeline and pricing, updated from official sources.",
  vi_dest_more: "See all {n} destinations →",
  vi_s1: "You give your destination and purpose", vi_s1p: "In one sentence, online or by phone.",
  vi_s2: "We check the applicable conditions", vi_s2p: "Visa type, documents, timelines and competent consulate.",
  vi_s3: "You entrust us with your file and passport", vi_s3p: "Online or at our avenue Louise office.",
  vi_s4: "We submit, follow up and collect", vi_s4p: "Consular appointment, submission and passport return.",
  vi_tar_h: "Our fees, by destination.",
  vi_tar_p: "Office fees, excluding consular charges. Each country page publishes the detailed table of the relevant consulate.",
  vi_grille: "See the full table →",
  vi_faq_h: "Questions about visas.",
  vi_cta_h: "Prepare your visa file.",
  vi_cta_p: "Tell us your destination and the purpose of your trip: we check the applicable conditions and the list of documents.",

  tr_eb: "Service · Translations",
  tr_h1a: "Translations",
  tr_h1g: "sworn & standard.",
  tr_sub: "Sworn for your official acts, or standard for information: we tell you which your procedure requires, then produce a faithful, compliant translation, accepted by Belgian and foreign authorities.",
  tr_stat: "languages handled",
  tr_f1: "languages", tr_f1p: "From and into any other language.",
  tr_f2: "translators", tr_f2p: "Sworn before the Belgian courts.",
  tr_f3: "standard timeline", tr_f3p: "Priority 48 h, express 24 h.",
  tr_f4: "drop-off & pickup", tr_f4p: "At the office or online.",
  tr_two_eb: "Two types of translation",
  tr_two_h: "Which does your procedure require?",
  tr_c1h: "Sworn translation", tr_c1p: "By a sworn translator, with stamp and signature. Required by administrations, civil registry, courts and foreign procedures.",
  tr_c2h: "Standard translation", tr_c2p: "For information, internal or commercial use: websites, brochures, correspondence, technical documents. The same quality standard.",
  tr_doc_eb: "Documents handled",
  tr_doc_h: "What we translate.",
  tr_doc_p: "Expertise covering all legal, commercial and academic needs. If your document isn’t listed, send it: you get an answer the same day.",
  tr_lang_eb: "Languages",
  tr_lang_h: "{n} languages, from Albanian to Wolof.",
  tr_lang_p: "Sworn translators for the main languages; standard translation for all others.",
  tr_tar_h: "Our prices, published.",
  tr_faq_h: "Questions about translation.",
  tr_cta_h: "Get your translation estimated.",
  tr_cta_p: "A legible scan is enough for a firm price and timeline.",

  lg_eb: "Service · Legalisations",
  lg_h1a: "Legalisations, apostilles",
  lg_h1g: "and official submissions.",
  lg_sub: "We handle the entire legalisation process of your documents with the Belgian authorities and foreign diplomatic missions. One point of contact, from the first counter to the last.",
  lg_stat: "authorities covered",
  lg_two_eb: "Two possible routes",
  lg_two_h: "Apostille, or full legalisation?",
  lg_c1h: "Hague apostille", lg_c1p: "For countries party to the Hague Convention: a single stamp from the FPS Foreign Affairs is enough. The fastest route.",
  lg_c2h: "Full legalisation", lg_c2p: "For other countries: the chain continues to the embassy or consulate of destination. We handle every link.",
  lg_ch_eb: "The legalisation chain",
  lg_ch_h: "The right counter, in the right order.",
  lg_ch_p: "Each link requires the right counter, the right order and the right documents. A mistake at the start is paid for at the end, in lost weeks.",
  lg_s1: "We check the applicable route", lg_s1p: "Hague apostille or full legalisation, depending on the destination country.",
  lg_s2: "Belgian legalisations", lg_s2p: "Court of First Instance, FPS Justice, FPS Foreign Affairs (apostille), chamber of commerce.",
  lg_s3: "Diplomatic mission", lg_s3p: "Submission to the country’s consulate or embassy when the apostille is not enough.",
  lg_s4: "Return of the completed file", lg_s4p: "In person at the office or by secure delivery.",
  lg_inst_eb: "Authorities covered",
  lg_inst_h: "We deal directly with:",
  lg_tar_h: "Official fees and our fees, distinguished.",
  lg_tar_p: "Official fees charged by the authority or consulate are billed at cost, against receipt, and are distinct from the office fees.",
  lg_faq_h: "Questions about legalisation.",
  lg_cta_h: "Need to legalise your documents?",
  lg_cta_p: "Get a precise analysis of your file and a detailed quote within 2 working hours.",

  ta_eb: "Pricing and timelines",
  ta_h1a: "Prices,",
  ta_h1g: "before you pick up the phone.",
  ta_sub: "The office publishes its prices. It’s every visitor’s first question, and the answer shouldn’t require a phone call. Official fees are always distinguished from the office fees.",
  ta_cta1: "Send my documents",
  ta_stat: "firm quote, in working hours",
  ta_trad: "Translation", ta_trad_h: "Standard and sworn translations.",
  ta_leg: "Legalisation", ta_leg_h: "Legalisations and apostilles.",
  ta_visa: "Visa", ta_visa_h: "Visas by destination.",
  ta_cov_eb: "What the price covers", ta_cov_h: "No nasty surprises.",
  ta_cov1h: "Official fees distinguished", ta_cov1p: "Amounts charged by authorities and consulates are billed at cost, against receipt.",
  ta_cov2h: "No hidden margin", ta_cov2p: "The office takes no margin on official fees; its fees are announced upfront.",
  ta_cov3h: "Firm quote in 2 h", ta_cov3p: "A scan of your documents is enough: you receive a line-by-line breakdown, in working hours.",
  ta_faq_h: "What you should know.",
  ta_cta_h: "A firm figure, not a range.",
  ta_cta_p: "Send the scan of your documents and your destination: you receive a line-by-line breakdown, official fees distinguished from the office fees.",
  ta_cta1b: "Get my quote",

  re_eb: "Resources",
  re_h1a: "Guides, procedures",
  re_h1g: "and document lists.",
  re_sub: "The answers to the questions that come up most on the phone, written once and for all. Available at any time, including when the office is closed.",
  re_stat: "country pages",
  re_g_eb: "Guides", re_g_h: "Understand before you travel.",
  re_g1h: "Sworn or standard translation?", re_g1p: "Understand when a sworn translator’s stamp is required, and when a standard translation is enough.",
  re_g2h: "The legalisation chain", re_g2p: "Hague apostille or full legalisation: the right order of counters, from court to embassy.",
  re_g3h: "Choosing your visa procedure", re_g3p: "Consular visa or e-visa: how to know what your destination requires.",
  re_g_more: "Read the guide",
  re_l_eb: "Document lists", re_l_h: "Know exactly what to gather.",
  re_l_p: "Each country page publishes the list of documents, the timeline and pricing, updated from official sources. {n} destinations.",
  re_l_btn: "See the country pages",
  re_faq_h: "The recurring questions.",
  re_cta_h: "A question these guides don’t cover?",
  re_cta_p: "The office answers clearly and quickly, Monday to Friday from 9 to 17, no lunch break.",

  ap_eb: "The office",
  ap_h1a: "The office,",
  ap_h1g: "avenue Louise.",
  ap_sub: "{r} guides individuals and businesses through their international document formalities: sworn translation, legalisation and travel visas. Technology saves us time; our experts remain at the heart of every file.",
  ap_stat: "views on the Google Local Guide profile",
  ap_visite: "Visit us",
  ap_lead: "An official formality abroad, without the administrative chore.",
  ap_metier: "Our work",
  ap_metier1: "An official formality often means several counters, a precise order to follow and exact documents to gather. We know these chains and we run them for you.",
  ap_metier2: "At each step, we tell you what to provide, at what price and within what timeframe — until the file is accepted.",
  ap_ph_lab: "Placeholder", ap_ph_h: "Travisum team photo to be added", ap_ph_p: "Professional photo taken at the avenue Louise office. Format 1600 × 1000 px.",
  ap_eng_eb: "Our commitments", ap_eng_h: "What we commit to.",
  ap_e1h: "Confidentiality", ap_e1p: "Passports, acts, diplomas: encrypted transmission, access limited to the team in charge, copies deleted after processing.",
  ap_e2h: "Published prices", ap_e2p: "Our prices are online. Official fees are billed at cost, against receipt, with no margin.",
  ap_e3h: "A single point of contact", ap_e3p: "From sworn translation to visa submission, one team follows your file end to end.",
  ap_conf_eb: "Confidentiality", ap_conf_h: "You hand us originals. We take that seriously.",
  ap_conf_p: "Passports, birth certificates, diplomas: these are documents you don’t hand over lightly.",
  ap_conf1: "Documents handled confidentially by our team.",
  ap_conf2: "Access limited to the team handling your file.",
  ap_conf3: "Digital copies deleted after processing.",
  ap_conf4: "Originals returned in person or by registered post.",
  ap_gg_eb: "Client reviews", ap_gg_h: "Our Google profile, soon connected to the site.",
  ap_gg_p: "Reviews published on the Google Business Profile of Travisum Louise Office will appear here automatically, with the real rating and count. No testimonial will be written.",
  ap_gg_btn: "View the Google profile", ap_gg_lab: "Placeholder", ap_gg_sub: "views on the Google Local Guide profile — figure to verify and update.",
  ap_ct_eb: "The office",
  ap_ct_tel: "Phone", ap_ct_mail: "Email", ap_ct_acces: "Access", ap_ct_acces_v: "metro Louise, trams 8 and 93, bus 54.",
  ap_ct_maps: "Open in Google Maps",
  ap_hor: "Monday to Friday, no lunch break",
  ap_cta_h: "Drop by the office, or send a scan.",
  ap_cta_p: "Appointments and personalised advice also available on request.",

  pp_dest: "Destination",
  pp_h1: "Visa",
  pp_sub: "Procedure, documents, timeline and pricing for an application filed from Belgium. The office prepares the file, books the consular appointment, submits and collects your passport.",
  pp_lancer: "Start my application",
  fil_accueil: "Home", fil_visas: "Visas", fil_aria: "Breadcrumb",
  pp_pieces_eb: "Documents to provide", pp_pieces_h: "Documents and procedures.",
  pp_prep_eb: "This destination", pp_prep_h: "Page being written.",
  pp_prep_p: "The office handles this destination, but the detail of the documents isn’t published yet. Contact us: the answer arrives the same day.",
  pp_autres_eb: "Other destinations", pp_autres_h: "See also.",
  pp_fiche: "Country page",
  pp_toutes: "The {n} destinations →",
  pp_cta_h: "Prepare your file {a}.",
  pp_cta_p: "Send us your passport as a scan and the purpose of your trip: we check the applicable conditions and the list of documents.",
  vol_tourisme: "Tourist visa", vol_business: "Business visa", vol_evisa: "e-Visa", vol_infos: "General information", vol_autre: "Other procedure",
  syn_lab: "Visa summary — up to date", syn_verif: "Verified on", syn_portail: "Official portal", syn_frais: "Official fees (indicative)", syn_delai: "Processing time", syn_validite: "Validity / stay", syn_reforme: "Recent change —", syn_source: "Source",
  syn_disc: "Indicative information, checked against an official source and subject to change. The decision rests with the consulate.",
  locale: "en-GB",
};

const D: Record<Locale, Dict> = { fr: FR, nl: NL, en: EN };

export function tp(lang: Locale): Dict {
  return D[lang] ?? FR;
}
