# -*- coding: utf-8 -*-
"""
Contenu de reference, releve sur travisum.com le 24 aout 2026.

Ces listes sont la propriete du client et sont factuelles : le devis
TRV-2026-01 (section 14) prevoit qu'elles soient « reprises telles quelles ».
Elles ne doivent pas etre reecrites sans validation.

Les copies brutes des pages sources sont dans reference/site-actuel/.
"""

# --------------------------------------------------------------------------
# Coordonnees
# --------------------------------------------------------------------------
CONTACT = {
    "raison": "Travisum Louise Office",
    "rue": "367, avenue Louise",
    "code_postal": "1050",
    "ville": "Bruxelles",
    "pays": "Belgique",
    "telephone": "02 642 00 25",
    "telephone_tel": "+3226420025",
    "mobile": "0485 948 935",
    "mobile_tel": "+32485948935",
    "email": "info@travisum.com",
    "horaires": "Du lundi au vendredi, de 9 h 00 à 17 h 00 sans interruption",
    "horaires_court": "Lun-ven 9 h – 17 h",
    "preuve": "Plus de 4.500.000 de vues sur Google Local Guide",
}

# --------------------------------------------------------------------------
# Langues de traduction (82, liste integrale du site actuel)
# --------------------------------------------------------------------------
LANGUES = [
    "Albanais",
    "Allemand",
    "Anglais",
    "Arabe",
    "Araméen",
    "Arménien",
    "Azeri",
    "Bambara",
    "Badini",
    "Berbère",
    "Bielorusse",
    "Bini",
    "Bosniaque",
    "Bulgare",
    "Cambodgien",
    "Cantonnais",
    "Chaldéen",
    "Coréen",
    "Croate",
    "Danois",
    "Dari",
    "Espagnol",
    "Ewe",
    "Farsi (iranien)",
    "Feyli",
    "Français",
    "Géorgien",
    "Grec",
    "Hébreu",
    "Hindi",
    "Hongrois",
    "Igbo",
    "Indénosien",
    "Italien",
    "Japonais",
    "Kazakh",
    "Khmer",
    "Kikongo",
    "Kinyarwanda",
    "Kirghize",
    "Kurde",
    "Laotien",
    "Latin",
    "Libanais",
    "Lingala",
    "Lituanien",
    "Macédonien",
    "Malinke",
    "Mandarin",
    "Mina",
    "Moldave",
    "Mongol",
    "Néerlandais",
    "Népalais",
    "Norvégien",
    "Ouzbek",
    "Papiaments",
    "Pashto",
    "Persan",
    "Pidgin (Nigéria)",
    "Polonais",
    "Portugais",
    "Roumain",
    "Russe",
    "Serbe",
    "Serbo-croate",
    "Slovaque",
    "Slovène",
    "Suédois",
    "Swahili",
    "Syriaque",
    "Syrien",
    "Tatare",
    "Tchèque",
    "Tchétchène",
    "Thai",
    "Turc",
    "Turkmen",
    "Ukrainien",
    "Urdu",
    "Vietnamien",
    "Wolof",
]

# Les douze langues qui recoivent une page dediee (devis, section 07)
LANGUES_PHARES = [
    "Neerlandais",
    "Anglais",
    "Arabe",
    "Espagnol",
    "Mandarin",
    "Russe",
    "Portugais",
    "Italien",
    "Allemand",
    "Polonais",
    "Roumain",
    "Turc",
]

# --------------------------------------------------------------------------
# Destinations visa (70, liste integrale du site actuel)
# --------------------------------------------------------------------------
DESTINATIONS = [
    "Algérie",
    "Angola",
    "Arabie Saoudite",
    "Bangladesh",
    "Bénin",
    "Biélorussie",
    "Birmanie/Myanmar",
    "Burkina Faso",
    "Burundi",
    "Cambodge",
    "Cameroun",
    "Chine",
    "Congo Brazzaville",
    "Congo RD",
    "Corée du Sud",
    "Cuba",
    "Djibouti",
    "Egypte",
    "Émirats Arabes Unis",
    "Érythrée",
    "États-Unis",
    "Éthiopie",
    "Gabon",
    "Ghana",
    "Guinée-Bissau",
    "Guinée Equatoriale",
    "Guinée (République)",
    "Inde",
    "Indonésie",
    "Iran",
    "Jordanie",
    "Kazakhstan",
    "Kenya",
    "Laos",
    "Liban",
    "Libéria",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritanie",
    "Mongolie",
    "Mozambique",
    "Namibie",
    "Népal",
    "Niger",
    "Nigéria",
    "Oman",
    "Ouganda",
    "Ouzbékistan",
    "Pakistan",
    "Papouasie Nouvelle Guinée",
    "Qatar",
    "République centrafricaine",
    "Russie",
    "Rwanda",
    "Sao Tomé et Principe",
    "Sierra Leone",
    "Soudan",
    "Sud Soudan",
    "Suriname",
    "Tadjikistan",
    "Tanzanie",
    "Tchad",
    "Thaïlande",
    "Togo",
    "Turkménistan",
    "Vietnam",
    "Yémen",
    "Zambie",
    "Zimbabwe",
]

# Les trois destinations mises en avant, avec les chiffres de la maquette
# Stitch. Pour toutes les autres le site actuel ne publie ni delai ni tarif :
# on affiche « Sur devis » plutot que d'inventer une valeur.
DESTINATIONS_PHARES = [
    {
        "nom": "Fédération de Russie",
        "court": "Russie", "lien": "visas/russie/",
        "drapeau": "RU",
        "type": "Visa consulaire",
        "delai": "10-15 jours",
        "prix": "165 EUR",
        "image": "assets/img/photos/visa-russie.jpg",
        "alt": "Place Rouge à Moscou — visa pour la Fédération de Russie",
    },
    {
        "nom": "République Populaire de Chine",
        "court": "Chine", "lien": "visas/chine/",
        "drapeau": "CN",
        "type": "Visa consulaire / e-visa",
        "delai": "6-8 jours",
        "prix": "126 EUR",
        "image": "assets/img/photos/visa-chine.jpg",
        "alt": "Ligne d’horizon de Shanghai — visa pour la République Populaire de Chine",
    },
    {
        "nom": "République de l’Inde",
        "court": "Inde", "lien": "visas/inde/",
        "drapeau": "IN",
        "type": "e-visa uniquement",
        "delai": "3-5 jours",
        "prix": "85 EUR",
        "image": "assets/img/photos/visa-inde.jpg",
        "alt": "Taj Mahal — visa pour la République de l’Inde",
    },
]

# --------------------------------------------------------------------------
# Instances aupres desquelles le bureau depose (page Legalisation)
# --------------------------------------------------------------------------
INSTANCES = [
    "SPF Justice",
    "Ministère des Affaires étrangères",
    "Tribunal de première instance",
    "Cours d’appel (Bruxelles, Liège, Namur, Mons, Nivelles et Anvers)",
    "Notaires",
    "Commission européenne",
    "Ambassades et consulats",
    "Universités et écoles",
    "Communes",
    "Chambres de commerce",
    "Communauté française",
    "Communauté flamande",
]

# --------------------------------------------------------------------------
# Documents traites
# --------------------------------------------------------------------------
DOCUMENTS_TRADUCTION = [
    "Acte de naissance (pour mariage, demande de nationalité, étude, etc.)",
    "Diplômes",
    "Certificat de mariage",
    "Acte de décès",
    "Apostille",
    "Documents commerciaux ou légaux (Actes, Procuration, Power of attorney, Factures, "
    "Brochure, etc.)",
    "Documents techniques",
    "Site web",
    "Attestations diverses",
    "Autres documents",
]

DOCUMENTS_LEGALISATION = [
    "Acte de naissance (pour mariage, demande de nationalité, étude, etc.)",
    "Diplômes",
    "Certificat de mariage",
    "Acte de décès",
    "Apostille",
    "Documents commerciaux (Actes, Procuration, Power of attorney, Factures, etc.)",
    "Attestations diverses",
    "Autres documents",
]

# --------------------------------------------------------------------------
# Service de facilitation de visa — texte du site actuel, mot pour mot
# --------------------------------------------------------------------------
PROCEDURE_VISA = [
    "Nous vous renseignons de façon claire sur les procédures de demandes de visas.",
    "Nous vérifions ensuite l’ensemble des documents fournis avant de les soumettre au "
    "consulat du pays concerné.",
    "Une fois le visa délivré par le consulat, nous vous livrons votre passeport au "
    "lieu de votre choix.",
]

# --------------------------------------------------------------------------
# Correspondance nom -> slug des fiches pays.
# Les slugs sont ceux du site actuel : les conserver preserve les URL
# (/visas/inde/) et donc les positions acquises sur Google.
# --------------------------------------------------------------------------
SLUGS = {
    'Algérie': 'algerie',
    'Angola': 'angola',
    'Arabie Saoudite': 'arabie-saoudite',
    'Bangladesh': 'bangladesh',
    'Birmanie/Myanmar': 'birmanie-myanmar',
    'Biélorussie': 'bielorussie',
    'Burkina Faso': 'burkina-faso',
    'Burundi': 'burundi',
    'Bénin': 'benin',
    'Cambodge': 'cambodge-2',
    'Cameroun': 'cameroun',
    'Chine': 'chine',
    'Congo Brazzaville': 'congo-brazzaville',
    'Congo RD': 'republique-democratique-du-congo',
    'Corée du Sud': 'coree-du-sud',
    'Cuba': 'cuba',
    'Djibouti': 'djibouti',
    'Egypte': 'egypte',
    'Gabon': 'gabon',
    'Ghana': 'ghana',
    'Guinée (République)': 'guinee-republique',
    'Guinée Equatoriale': 'guinee-equatoriale',
    'Guinée-Bissau': 'guinee-bissau',
    'Inde': 'inde',
    'Indonésie': 'indonesie',
    'Iran': 'iran',
    'Jordanie': 'jordanie',
    'Kazakhstan': 'kazakhstan',
    'Kenya': 'kenya',
    'Laos': 'laos',
    'Liban': 'liban',
    'Libéria': 'liberia',
    'Madagascar': 'madagascar',
    'Malawi': 'malawi',
    'Mali': 'mali',
    'Mauritanie': 'mauritanie',
    'Mongolie': 'mongolie-2',
    'Mozambique': 'mozambique',
    'Namibie': 'namibie',
    'Niger': 'niger',
    'Nigéria': 'nigeria',
    'Népal': 'nepal',
    'Oman': 'oman',
    'Ouganda': 'ouganda',
    'Ouzbékistan': 'ouzbekistan',
    'Pakistan': 'pakistan',
    'Papouasie Nouvelle Guinée': 'papouasie-nouvelle-guinee',
    'Qatar': 'qatar',
    'Russie': 'russie',
    'Rwanda': 'rwanda',
    'République centrafricaine': 'republique-centrafricaine',
    'Sao Tomé et Principe': 'sao-tome-et-principe',
    'Sierra Leone': 'sierra-leone',
    'Soudan': 'soudan',
    'Sud Soudan': 'sud-soudan',
    'Suriname': 'suriname',
    'Tadjikistan': 'tadjikistan',
    'Tanzanie': 'tanzanie',
    'Tchad': 'tchad',
    'Thaïlande': 'thailande',
    'Togo': 'togo',
    'Turkménistan': 'turkmenistan',
    'Vietnam': 'vietnam',
    'Yémen': 'yemen',
    'Zambie': 'zambie',
    'Zimbabwe': 'zimbabwe',
    'Émirats Arabes Unis': 'emirats-arabes-unis',
    'Érythrée': 'erythree',
    'États-Unis': 'etats-unis-2',
    'Éthiopie': 'ethiopie',
}

# --------------------------------------------------------------------------
# Article defini par pays : « visa pour l'Inde », « pour le Bangladesh »,
# « pour les Etats-Unis », « pour Cuba ». Le francais ne se devine pas.
# --------------------------------------------------------------------------
ARTICLE = {
    'Algérie': 'pour l’Algérie',
    'Angola': 'pour l’Angola',
    'Arabie Saoudite': 'pour l’Arabie Saoudite',
    'Bangladesh': 'pour le Bangladesh',
    'Birmanie/Myanmar': 'pour la Birmanie/Myanmar',
    'Biélorussie': 'pour la Biélorussie',
    'Burkina Faso': 'pour le Burkina Faso',
    'Burundi': 'pour le Burundi',
    'Bénin': 'pour le Bénin',
    'Cambodge': 'pour le Cambodge',
    'Cameroun': 'pour le Cameroun',
    'Chine': 'pour la Chine',
    'Congo Brazzaville': 'pour le Congo Brazzaville',
    'Congo RD': 'pour le Congo RD',
    'Corée du Sud': 'pour la Corée du Sud',
    'Cuba': 'pour Cuba',
    'Djibouti': 'pour Djibouti',
    'Egypte': 'pour l’Egypte',
    'Gabon': 'pour le Gabon',
    'Ghana': 'pour le Ghana',
    'Guinée (République)': 'pour la Guinée (République)',
    'Guinée Equatoriale': 'pour la Guinée Equatoriale',
    'Guinée-Bissau': 'pour la Guinée-Bissau',
    'Inde': 'pour l’Inde',
    'Indonésie': 'pour l’Indonésie',
    'Iran': 'pour l’Iran',
    'Jordanie': 'pour la Jordanie',
    'Kazakhstan': 'pour le Kazakhstan',
    'Kenya': 'pour le Kenya',
    'Laos': 'pour le Laos',
    'Liban': 'pour le Liban',
    'Libéria': 'pour le Libéria',
    'Madagascar': 'pour Madagascar',
    'Malawi': 'pour le Malawi',
    'Mali': 'pour le Mali',
    'Mauritanie': 'pour la Mauritanie',
    'Mongolie': 'pour la Mongolie',
    'Mozambique': 'pour le Mozambique',
    'Namibie': 'pour la Namibie',
    'Niger': 'pour le Niger',
    'Nigéria': 'pour le Nigéria',
    'Népal': 'pour le Népal',
    'Oman': 'pour Oman',
    'Ouganda': 'pour l’Ouganda',
    'Ouzbékistan': 'pour l’Ouzbékistan',
    'Pakistan': 'pour le Pakistan',
    'Papouasie Nouvelle Guinée': 'pour la Papouasie Nouvelle Guinée',
    'Qatar': 'pour le Qatar',
    'Russie': 'pour la Russie',
    'Rwanda': 'pour le Rwanda',
    'République centrafricaine': 'pour la République centrafricaine',
    'Sao Tomé et Principe': 'pour Sao Tomé et Principe',
    'Sierra Leone': 'pour la Sierra Leone',
    'Soudan': 'pour le Soudan',
    'Sud Soudan': 'pour le Sud Soudan',
    'Suriname': 'pour le Suriname',
    'Tadjikistan': 'pour le Tadjikistan',
    'Tanzanie': 'pour la Tanzanie',
    'Tchad': 'pour le Tchad',
    'Thaïlande': 'pour la Thaïlande',
    'Togo': 'pour le Togo',
    'Turkménistan': 'pour le Turkménistan',
    'Vietnam': 'pour le Vietnam',
    'Yémen': 'pour le Yémen',
    'Zambie': 'pour la Zambie',
    'Zimbabwe': 'pour le Zimbabwe',
    'Émirats Arabes Unis': 'pour les Émirats Arabes Unis',
    'Érythrée': 'pour l’Érythrée',
    'États-Unis': 'pour les États-Unis',
    'Éthiopie': 'pour l’Éthiopie',
}
